version: 2

project_name: oktsec

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/oktsec
    binary: oktsec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/oktsec/oktsec/cmd/oktsec/commands.version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/oktsec/oktsec:{{ .Version }}"
    image_templates:
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-amd64"
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-arm64"
  - name_template: "ghcr.io/oktsec/oktsec:latest"
    image_templates:
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-amd64"
      - "ghcr.io/oktsec/oktsec:{{ .Version }}-arm64"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
