package commands

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/oktsec/oktsec/internal/config"
	"github.com/oktsec/oktsec/internal/dashboard"
	"github.com/oktsec/oktsec/internal/discover"
	"github.com/oktsec/oktsec/internal/identity"
	"github.com/oktsec/oktsec/internal/proxy"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

type runOpts struct {
	port     int
	bind     string
	enforce  bool
	skipWrap bool
}

func newRunCmd() *cobra.Command {
	var opts runOpts

	cmd := &cobra.Command{
		Use:   "run",
		Short: "Setup and start oktsec in one step",
		Long: `Discovers MCP servers, generates config, and starts the proxy server.

If no config file exists, runs first-time setup automatically:
  1. Scans for MCP clients and servers on this machine
  2. Generates config with observe-mode defaults
  3. Generates Ed25519 keypairs for each discovered agent
  4. Wraps discovered MCP servers through oktsec proxy
  5. Starts the proxy server with dashboard

If a config already exists, starts the server directly.

Config is resolved in order: --config flag, $OKTSEC_CONFIG env var,
./oktsec.yaml (local), ~/.oktsec/config.yaml (home).`,
		Example: `  oktsec run
  oktsec run --port 9000
  oktsec run --enforce
  oktsec run --skip-wrap`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return executeRun(opts)
		},
	}

	cmd.Flags().IntVar(&opts.port, "port", 0, "override server port")
	cmd.Flags().StringVar(&opts.bind, "bind", "", "address to bind (default: 127.0.0.1)")
	cmd.Flags().BoolVar(&opts.enforce, "enforce", false, "start in enforcement mode (block malicious requests)")
	cmd.Flags().BoolVar(&opts.skipWrap, "skip-wrap", false, "generate config only, don't modify MCP client configs")
	return cmd
}

func executeRun(opts runOpts) error {
	configPath := cfgFile

	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		fmt.Println()
		fmt.Println("  oktsec — first-time setup")
		fmt.Println("  ────────────────────────────────────────")
		fmt.Println()

		if err := autoSetup(configPath, opts); err != nil {
			return fmt.Errorf("setup failed: %w", err)
		}
	}

	return startServer(configPath, opts)
}

func autoSetup(configPath string, opts runOpts) error {
	// Ensure parent directory exists (e.g. ~/.oktsec/)
	if dir := filepath.Dir(configPath); dir != "." {
		_ = os.MkdirAll(dir, 0o700)
	}

	// Step 1: Discover
	fmt.Println("  Scanning for MCP servers...")
	result, err := discover.Scan()
	if err != nil {
		return err
	}

	if result.TotalServers() == 0 {
		fmt.Println("  No MCP servers found.")
		fmt.Println()
		fmt.Println("  Starting with empty config (0 agents).")
		fmt.Println("  Add agents via the dashboard after startup.")
		fmt.Println()
		if err := writeMinimalConfig(configPath); err != nil {
			return err
		}
		return ensureSecrets(configPath)
	}

	fmt.Printf("  Found %d server(s) across %d client(s):\n\n", result.TotalServers(), result.TotalClients())
	for _, cr := range result.Clients {
		if len(cr.Servers) == 0 {
			continue
		}
		names := make([]string, len(cr.Servers))
		for i, s := range cr.Servers {
			names[i] = s.Name
		}
		fmt.Printf("    %-16s  %s\n", discover.ClientDisplayName(cr.Client), strings.Join(names, ", "))
	}
	fmt.Println()

	// Step 2: Generate config + keypairs
	keysDir := config.DefaultKeysDir()
	if err := os.MkdirAll(keysDir, 0o700); err != nil {
		return fmt.Errorf("creating keys directory: %w", err)
	}

	type agentYAML struct {
		CanMessage []string `yaml:"can_message,flow"`
		Source     string   `yaml:"source"`
		RiskLevel  string   `yaml:"risk_level"`
	}

	agents := make(map[string]agentYAML)
	for _, entry := range result.AllServers() {
		name := entry.Server.Name
		risk := assessRisk(entry.Server)
		agents[name] = agentYAML{
			CanMessage: []string{"*"},
			Source:     entry.Client,
			RiskLevel:  risk,
		}

		kp, err := identity.GenerateKeypair(name)
		if err != nil {
			return fmt.Errorf("generating keypair for %s: %w", name, err)
		}
		if err := kp.Save(keysDir); err != nil {
			return fmt.Errorf("saving keypair for %s: %w", name, err)
		}
	}

	absConfig, err := filepath.Abs(configPath)
	if err != nil {
		absConfig = configPath
	}

	dbPath := config.DefaultDBPath()

	port := 8080
	if opts.port != 0 {
		port = opts.port
	}

	cfgMap := map[string]any{
		"version": "1",
		"server": map[string]any{
			"port":      port,
			"log_level": "info",
		},
		"identity": map[string]any{
			"keys_dir":          keysDir,
			"require_signature": false,
		},
		"db_path": dbPath,
		"agents":  agents,
	}

	data, err := yaml.Marshal(cfgMap)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := "# Generated by oktsec run\n# Mode: observe (audit-only, no blocking)\n"
	if err := os.WriteFile(configPath, append([]byte(header), data...), 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Println("  Generated:")
	fmt.Printf("    Config:   %s\n", absConfig)
	fmt.Printf("    Keys:     %s/\n", keysDir)
	fmt.Printf("    Audit DB: %s\n", dbPath)
	fmt.Println()

	// Step 3: Generate secrets (.env)
	if err := ensureSecrets(configPath); err != nil {
		return err
	}

	// Step 4: Wrap
	if !opts.skipWrap {
		fmt.Println("  Wrapping MCP servers...")

		wrapOpts := discover.WrapOpts{
			Enforce:    opts.enforce,
			ConfigPath: absConfig,
		}
		results := discover.WrapAllClients(wrapOpts)

		totalWrapped := 0
		for _, r := range results {
			name := discover.ClientDisplayName(r.Client)
			if r.Error != nil {
				fmt.Printf("    %-16s  error: %s\n", name, *r.Error)
				continue
			}
			if r.Wrapped > 0 {
				fmt.Printf("    %-16s  %d server(s) wrapped\n", name, r.Wrapped)
				totalWrapped += r.Wrapped
			}
		}

		if totalWrapped > 0 {
			fmt.Printf("\n    %d server(s) now routing through oktsec.\n", totalWrapped)
		}
		fmt.Println()
	}

	fmt.Println("  Setup complete. Starting server...")
	fmt.Println()
	return nil
}

// ensureSecrets creates the .env file with auto-generated secrets if it doesn't exist.
func ensureSecrets(configPath string) error {
	envPath := filepath.Join(filepath.Dir(configPath), ".env")
	if err := config.EnsureEnvFile(envPath); err != nil {
		return fmt.Errorf("creating secrets file: %w", err)
	}
	return nil
}

func writeMinimalConfig(configPath string) error {
	dbPath := config.DefaultDBPath()
	keysDir := config.DefaultKeysDir()
	cfgMap := map[string]any{
		"version": "1",
		"server": map[string]any{
			"port":      8080,
			"log_level": "info",
		},
		"identity": map[string]any{
			"keys_dir":          keysDir,
			"require_signature": false,
		},
		"db_path": dbPath,
		"agents":  map[string]any{},
	}

	data, err := yaml.Marshal(cfgMap)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := "# Generated by oktsec run\n# No MCP servers found. Add agents via the dashboard.\n"
	return os.WriteFile(configPath, append([]byte(header), data...), 0o600)
}

func startServer(configPath string, opts runOpts) error {
	cfg, err := config.Load(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "\n  Warning: could not load %s (%v)\n", configPath, err)
		fmt.Fprintf(os.Stderr, "  Starting with default config.\n\n")
		cfg = config.Defaults()
	}

	// Load secrets from .env (adjacent to config)
	envPath := filepath.Join(filepath.Dir(configPath), ".env")
	if env, _ := config.LoadEnv(envPath); env != nil {
		config.ApplyEnv(cfg, env)
	}

	if opts.port != 0 {
		cfg.Server.Port = opts.port
	}
	if opts.bind != "" {
		cfg.Server.Bind = opts.bind
	}

	if err := cfg.Validate(); err != nil {
		return err
	}

	level := slog.LevelInfo
	switch cfg.Server.LogLevel {
	case "debug":
		level = slog.LevelDebug
	case "warn":
		level = slog.LevelWarn
	case "error":
		level = slog.LevelError
	}

	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: level}))

	dashboard.Version = version
	proxy.Version = version
	srv, err := proxy.NewServer(cfg, configPath, logger)
	if err != nil {
		return err
	}

	printBanner(cfg, srv.DashboardCode())

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	errCh := make(chan error, 1)
	go func() {
		errCh <- srv.Start()
	}()

	select {
	case err := <-errCh:
		return err
	case <-ctx.Done():
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		return srv.Shutdown(shutdownCtx)
	}
}
