package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/oktsec/oktsec/internal/discover"
	"github.com/oktsec/oktsec/internal/identity"
	"gopkg.in/yaml.v3"

	"github.com/spf13/cobra"
)

func newSetupCmd() *cobra.Command {
	var (
		keysDir   string
		configOut string
		enforce   bool
		skipWrap  bool
	)

	cmd := &cobra.Command{
		Use:   "setup",
		Short: "Discover, configure, and protect all MCP servers in one step",
		Long: `Runs the full onboarding flow:
  1. Discovers all MCP clients and servers on this machine
  2. Generates oktsec.yaml with sensible defaults
  3. Generates Ed25519 keypairs for each agent
  4. Wraps all discovered MCP servers through oktsec proxy
  5. Shows what's protected and how to start the dashboard`,
		Example: `  oktsec setup
  oktsec setup --enforce
  oktsec setup --skip-wrap`,
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Println()
			fmt.Println("  oktsec setup")
			fmt.Println("  ────────────────────────────────────────")
			fmt.Println()

			// Step 1: Discover
			fmt.Println("  Scanning for MCP clients...")
			result, err := discover.Scan()
			if err != nil {
				return err
			}

			if result.TotalServers() == 0 {
				fmt.Println()
				fmt.Println("  No MCP servers found on this machine.")
				fmt.Println()
				fmt.Println("  Checked 17 clients: Claude Desktop, Cursor, VS Code, Cline,")
				fmt.Println("  Windsurf, Claude Code, Roo Code, and more.")
				fmt.Println()
				fmt.Println("  Install an MCP server first, then run 'oktsec setup' again.")
				return nil
			}

			fmt.Printf("  Found %d server(s) across %d client(s):\n\n", result.TotalServers(), result.TotalClients())
			for _, cr := range result.Clients {
				if len(cr.Servers) == 0 {
					continue
				}
				names := make([]string, len(cr.Servers))
				for i, s := range cr.Servers {
					names[i] = s.Name
				}
				fmt.Printf("    %-16s  %s\n", discover.ClientDisplayName(cr.Client), strings.Join(names, ", "))
			}
			fmt.Println()

			// Step 2: Generate config
			fmt.Println("  Generating configuration...")

			if err := os.MkdirAll(keysDir, 0o700); err != nil {
				return fmt.Errorf("creating keys directory: %w", err)
			}

			type agentYAML struct {
				CanMessage []string `yaml:"can_message,flow"`
				Source     string   `yaml:"source"`
				RiskLevel  string   `yaml:"risk_level"`
			}

			agents := make(map[string]agentYAML)
			for _, entry := range result.AllServers() {
				name := entry.Server.Name
				risk := assessRisk(entry.Server)
				agents[name] = agentYAML{
					CanMessage: []string{"*"},
					Source:     entry.Client,
					RiskLevel:  risk,
				}

				// Generate keypair
				kp, err := identity.GenerateKeypair(name)
				if err != nil {
					return fmt.Errorf("generating keypair for %s: %w", name, err)
				}
				if err := kp.Save(keysDir); err != nil {
					return fmt.Errorf("saving keypair for %s: %w", name, err)
				}
			}

			// Resolve absolute config path for proxy passthrough
			absConfig, err := filepath.Abs(configOut)
			if err != nil {
				absConfig = configOut
			}

			// Use shared DB path
			dbPath := defaultDBPath()

			cfg := map[string]any{
				"version": "1",
				"server": map[string]any{
					"port":      8080,
					"log_level": "info",
				},
				"identity": map[string]any{
					"keys_dir":          keysDir,
					"require_signature": false,
				},
				"db_path": dbPath,
				"agents":  agents,
			}

			data, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("marshaling config: %w", err)
			}

			header := "# Generated by oktsec setup\n# Mode: observe (audit-only, no blocking)\n# Edit this file to customize policies, then restart.\n"
			if err := os.WriteFile(configOut, append([]byte(header), data...), 0o644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}

			fmt.Printf("    Config:   %s\n", absConfig)
			fmt.Printf("    Keys:     %s/\n", keysDir)
			fmt.Printf("    Audit DB: %s\n", dbPath)
			fmt.Println()

			// Step 3: Wrap
			if skipWrap {
				fmt.Println("  Skipping wrap (--skip-wrap).")
				fmt.Println("  Run 'oktsec wrap --all' when ready.")
			} else {
				fmt.Println("  Wrapping MCP servers...")

				opts := discover.WrapOpts{
					Enforce:    enforce,
					ConfigPath: absConfig,
				}
				results := discover.WrapAllClients(opts)

				totalWrapped := 0
				for _, r := range results {
					name := discover.ClientDisplayName(r.Client)
					if r.Error != nil {
						fmt.Printf("    %-16s  error: %s\n", name, *r.Error)
						continue
					}
					if r.Wrapped > 0 {
						fmt.Printf("    %-16s  %d server(s) wrapped\n", name, r.Wrapped)
						totalWrapped += r.Wrapped
					}
				}

				if totalWrapped > 0 {
					fmt.Printf("\n    %d server(s) now routing through oktsec.\n", totalWrapped)
				}
			}

			// Step 4: Summary
			mode := "observe"
			if enforce {
				mode = "enforce"
			}

			fmt.Println()
			fmt.Println("  ────────────────────────────────────────")
			fmt.Println("  Setup complete!")
			fmt.Println("  ────────────────────────────────────────")
			fmt.Println()
			fmt.Printf("  Mode:    %s", mode)
			if mode == "observe" {
				fmt.Print("  (logs everything, blocks nothing)")
			}
			fmt.Println()
			fmt.Printf("  Agents:  %d\n", len(agents))
			fmt.Printf("  Rules:   175 detection rules active\n")
			fmt.Println()
			fmt.Println("  Next steps:")
			fmt.Println()
			if !skipWrap {
				fmt.Println("    1. Restart your MCP clients (Claude Desktop, Cursor, etc.)")
				fmt.Println("    2. Start the dashboard:")
				fmt.Println()
				fmt.Printf("         oktsec serve --config %s\n", configOut)
				fmt.Println()
				fmt.Println("    3. Use your MCP tools normally — oktsec scans in the background")
				fmt.Println("    4. Check the dashboard at http://127.0.0.1:8080/dashboard")
			} else {
				fmt.Println("    1. Run 'oktsec wrap --all' to start protecting")
				fmt.Println("    2. Run 'oktsec serve' to start the dashboard")
			}
			fmt.Println()
			fmt.Println("  To watch live:")
			fmt.Println()
			fmt.Println("    oktsec logs --live")
			fmt.Println()
			if mode == "observe" {
				fmt.Println("  To switch to enforcement mode (block malicious requests):")
				fmt.Println()
				fmt.Println("    oktsec wrap --all --enforce")
				fmt.Println()
			}
			fmt.Println("  To undo everything:")
			fmt.Println()
			fmt.Println("    oktsec unwrap <client>")
			fmt.Println()

			return nil
		},
	}

	cmd.Flags().StringVar(&keysDir, "keys", "./keys", "directory for generated keypairs")
	cmd.Flags().StringVar(&configOut, "config", "oktsec.yaml", "output config file path")
	cmd.Flags().BoolVar(&enforce, "enforce", false, "start in enforcement mode (block malicious requests)")
	cmd.Flags().BoolVar(&skipWrap, "skip-wrap", false, "generate config only, don't modify client configs")
	return cmd
}
