package commands

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/oktsec/oktsec/internal/config"
	"github.com/oktsec/oktsec/internal/identity/resolve"
	"github.com/spf13/cobra"
)

// validTokenTypes lists the token types the CLI is willing to mint. The
// resolver can recognize all three even though only gateway_bearer is
// wired into a surface today; we accept the others now so an operator
// can pre-create proxy/hook tokens against the same config and have them
// activate automatically when those surfaces ship.
var validTokenTypes = map[string]bool{
	"gateway_bearer": true,
	"proxy_basic":    true,
	"hook_bearer":    true,
}

// tokenIDPrefixes maps a token type to the short prefix used when the
// CLI auto-generates a token id. Operators rarely look at the random
// suffix; they use principal + date to identify a token in `list`.
var tokenIDPrefixes = map[string]string{
	"gateway_bearer": "gw",
	"proxy_basic":    "proxy",
	"hook_bearer":    "hook",
}

func newTokensCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tokens",
		Short: "Create, list, and revoke principal tokens",
		Long: `Manage authentication tokens for principals (agents, services).

Tokens authenticate clients to Oktsec surfaces:
  - gateway_bearer: MCP HTTP gateway
  - proxy_basic:    HTTP forward proxy (reserved; not yet wired)
  - hook_bearer:    hook adapter        (reserved; not yet wired)

Raw token values are shown only once at creation. Only the salted
SHA-256 hash is persisted in the config file.`,
	}
	cmd.AddCommand(
		newTokensCreateCmd(),
		newTokensListCmd(),
		newTokensRevokeCmd(),
	)
	return cmd
}

// ── create ──

func newTokensCreateCmd() *cobra.Command {
	var (
		principalID string
		tokenType   string
		tokenID     string
		expiresIn   string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new token for a principal (auto-creates the principal if missing)",
		RunE: func(cmd *cobra.Command, args []string) error {
			if principalID == "" {
				return fmt.Errorf("--principal is required")
			}
			if !validTokenTypes[tokenType] {
				return fmt.Errorf("--type must be one of: gateway_bearer, proxy_basic, hook_bearer")
			}
			expiresAt := ""
			if expiresIn != "" {
				exp, err := parseExpiry(expiresIn, time.Now().UTC())
				if err != nil {
					return err
				}
				expiresAt = exp
			}
			return createToken(cfgFile, principalID, tokenType, tokenID, expiresAt, os.Stdout)
		},
	}
	cmd.Flags().StringVar(&principalID, "principal", "", "principal id (created if missing)")
	cmd.Flags().StringVar(&tokenType, "type", "gateway_bearer", "token type: gateway_bearer | proxy_basic | hook_bearer")
	cmd.Flags().StringVar(&tokenID, "token-id", "", "explicit token id (autogenerated when empty)")
	cmd.Flags().StringVar(&expiresIn, "expires", "", "token lifetime (e.g. 24h, 7d, 30d, 1y); empty = no expiry")
	return cmd
}

// createToken runs the actual mutation. Split out from the cobra wiring
// so tests can drive it with an arbitrary config path and capture the
// printed output.
func createToken(cfgPath, principalID, tokenType, tokenIDOpt, expiresAt string, out *os.File) error {
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	// Auto-create the principal so the operator can go from zero to
	// "client connected" in one command. The output explicitly reports
	// the creation so it never feels like a silent YAML mutation.
	principalCreated := false
	idx := indexOfPrincipal(cfg.Identity.Principals, principalID)
	if idx < 0 {
		cfg.Identity.Principals = append(cfg.Identity.Principals, config.PrincipalConfig{
			ID:          principalID,
			DisplayName: principalID,
			Kind:        "agent",
		})
		idx = len(cfg.Identity.Principals) - 1
		principalCreated = true
	}

	// Reject duplicate token ids before generating any secret material.
	if tokenIDOpt != "" {
		for _, t := range cfg.Identity.Principals[idx].Tokens {
			if t.ID == tokenIDOpt {
				return fmt.Errorf("token id %q already exists for principal %q", tokenIDOpt, principalID)
			}
		}
	}

	// Map the CLI string to the resolver's TokenType for hash generation.
	tt, ok := tokenTypeFromCLI(tokenType)
	if !ok {
		return fmt.Errorf("invalid token type %q", tokenType)
	}
	raw, hash, err := resolve.GenerateRawToken(tt)
	if err != nil {
		return fmt.Errorf("generating token: %w", err)
	}

	tokID := tokenIDOpt
	if tokID == "" {
		tokID, err = autogenTokenID(tokenType, principalID, time.Now().UTC())
		if err != nil {
			return fmt.Errorf("generating token id: %w", err)
		}
	}
	cfg.Identity.Principals[idx].Tokens = append(cfg.Identity.Principals[idx].Tokens, config.PrincipalTokenConfig{
		ID:        tokID,
		Type:      tokenType,
		Hash:      hash,
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		ExpiresAt: expiresAt,
	})

	if err := cfg.Save(cfgPath); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}

	if principalCreated {
		fmt.Fprintf(out, "Created principal %q with kind=agent.\n", principalID)
	}
	fmt.Fprintf(out, "Created token %q for principal %q.\n", tokID, principalID)
	if expiresAt != "" {
		fmt.Fprintf(out, "Expires at %s.\n", expiresAt)
	}
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Raw token (shown once, copy it now):")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "  %s\n", raw)
	fmt.Fprintln(out)
	switch tokenType {
	case "gateway_bearer":
		fmt.Fprintln(out, "Use it in your MCP client's Authorization header:")
		fmt.Fprintln(out)
		fmt.Fprintf(out, "  Authorization: Bearer %s\n", raw)
	case "proxy_basic":
		fmt.Fprintln(out, "Use it as the username in your proxy URL (password empty):")
		fmt.Fprintln(out)
		fmt.Fprintf(out, "  HTTP_PROXY=http://%s:@127.0.0.1:8083\n", raw)
	case "hook_bearer":
		fmt.Fprintln(out, "Use it in your hook client's Authorization header:")
		fmt.Fprintln(out)
		fmt.Fprintf(out, "  Authorization: Bearer %s\n", raw)
	}
	fmt.Fprintln(out)
	fmt.Fprintln(out, "The hash has been saved to your config. The raw value above will not be displayed again.")
	fmt.Fprintln(out, "Reload the gateway (SIGHUP) for the new token to take effect immediately.")
	return nil
}

// ── list ──

func newTokensListCmd() *cobra.Command {
	var principalFilter string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List principals and their tokens (raw values are never displayed)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return listTokens(cfgFile, principalFilter, os.Stdout)
		},
	}
	cmd.Flags().StringVar(&principalFilter, "principal", "", "limit output to one principal id")
	return cmd
}

func listTokens(cfgPath, principalFilter string, out *os.File) error {
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	w := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "PRINCIPAL\tTOKEN ID\tTYPE\tSTATUS\tCREATED\tEXPIRES")
	now := time.Now().UTC()
	any := false
	for _, p := range cfg.Identity.Principals {
		if principalFilter != "" && p.ID != principalFilter {
			continue
		}
		for _, t := range p.Tokens {
			any = true
			expDisplay := t.ExpiresAt
			if expDisplay == "" {
				expDisplay = "-"
			}
			fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\t%s\n",
				p.ID, t.ID, t.Type, tokenStatus(t, now), valueOrDash(t.CreatedAt), expDisplay)
		}
	}
	if !any {
		fmt.Fprintln(w, "(no tokens)")
	}
	return w.Flush()
}

// ── revoke ──

func newTokensRevokeCmd() *cobra.Command {
	var (
		principalID string
		tokenID     string
	)
	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Revoke a token (sets revoked_at; the row stays in config for audit)",
		RunE: func(cmd *cobra.Command, args []string) error {
			if principalID == "" || tokenID == "" {
				return fmt.Errorf("--principal and --token are required")
			}
			return revokeToken(cfgFile, principalID, tokenID, os.Stdout)
		},
	}
	cmd.Flags().StringVar(&principalID, "principal", "", "principal id")
	cmd.Flags().StringVar(&tokenID, "token", "", "token id to revoke")
	return cmd
}

func revokeToken(cfgPath, principalID, tokenID string, out *os.File) error {
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	idx := indexOfPrincipal(cfg.Identity.Principals, principalID)
	if idx < 0 {
		return fmt.Errorf("principal %q not found", principalID)
	}
	tokIdx := -1
	for i, t := range cfg.Identity.Principals[idx].Tokens {
		if t.ID == tokenID {
			tokIdx = i
			break
		}
	}
	if tokIdx < 0 {
		return fmt.Errorf("token %q not found for principal %q", tokenID, principalID)
	}
	if cfg.Identity.Principals[idx].Tokens[tokIdx].RevokedAt != "" {
		fmt.Fprintf(out, "Token %q for principal %q is already revoked.\n", tokenID, principalID)
		return nil
	}
	cfg.Identity.Principals[idx].Tokens[tokIdx].RevokedAt = time.Now().UTC().Format(time.RFC3339)
	if err := cfg.Save(cfgPath); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}
	fmt.Fprintf(out, "Revoked token %q for principal %q.\n", tokenID, principalID)
	fmt.Fprintln(out, "Reload the gateway (SIGHUP) for the change to take effect immediately.")
	return nil
}

// ── helpers ──

func indexOfPrincipal(principals []config.PrincipalConfig, id string) int {
	for i, p := range principals {
		if p.ID == id {
			return i
		}
	}
	return -1
}

// tokenStatus folds expires_at and revoked_at into one human label.
func tokenStatus(t config.PrincipalTokenConfig, now time.Time) string {
	if t.RevokedAt != "" {
		return "revoked"
	}
	if t.ExpiresAt != "" {
		exp, err := time.Parse(time.RFC3339, t.ExpiresAt)
		if err != nil {
			return "invalid-expiry"
		}
		if !now.Before(exp) {
			return "expired"
		}
	}
	return "active"
}

func valueOrDash(s string) string {
	if s == "" {
		return "-"
	}
	// Trim sub-second precision for display; keep day + time only.
	if t, err := time.Parse(time.RFC3339, s); err == nil {
		return t.Format("2006-01-02")
	}
	return s
}

func tokenTypeFromCLI(s string) (resolve.TokenType, bool) {
	switch s {
	case "gateway_bearer":
		return resolve.TokenTypeGatewayBearer, true
	case "proxy_basic":
		return resolve.TokenTypeProxyBasic, true
	case "hook_bearer":
		return resolve.TokenTypeHookBearer, true
	}
	return "", false
}

// expiryUnitRe matches the human duration syntax this CLI accepts on
// top of Go's time.ParseDuration: <int><unit> where unit ∈ {d, w, y}.
var expiryUnitRe = regexp.MustCompile(`^(\d+)([dwy])$`)

// parseExpiry accepts either Go's standard duration syntax (90s, 24h, etc.)
// or the human shortcuts d/w/y. Returns the absolute expiry timestamp in
// RFC3339 UTC so it can be persisted directly.
func parseExpiry(s string, now time.Time) (string, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", fmt.Errorf("empty duration")
	}
	if d, err := time.ParseDuration(s); err == nil {
		return now.Add(d).Format(time.RFC3339), nil
	}
	if m := expiryUnitRe.FindStringSubmatch(strings.ToLower(s)); m != nil {
		n, err := strconv.Atoi(m[1])
		if err != nil || n <= 0 {
			return "", fmt.Errorf("invalid duration %q", s)
		}
		var d time.Duration
		switch m[2] {
		case "d":
			d = time.Duration(n) * 24 * time.Hour
		case "w":
			d = time.Duration(n) * 7 * 24 * time.Hour
		case "y":
			// Calendar years would require time.AddDate; for token
			// lifetimes a fixed 365 days is the safer, reproducible
			// choice — operators set explicit dates if they need exact
			// anniversaries.
			d = time.Duration(n) * 365 * 24 * time.Hour
		}
		return now.Add(d).Format(time.RFC3339), nil
	}
	return "", fmt.Errorf("invalid duration %q (use 24h, 7d, 30d, 1y, ...)", s)
}

// autogenTokenID builds a stable, human-readable token id with a short
// random suffix so two tokens for the same principal on the same day do
// not collide. Format: <type-prefix>-<principal>-<YYYY-MM-DD>-<6 hex>.
func autogenTokenID(tokenType, principalID string, now time.Time) (string, error) {
	prefix, ok := tokenIDPrefixes[tokenType]
	if !ok {
		return "", fmt.Errorf("no id prefix for token type %q", tokenType)
	}
	suffix := make([]byte, 3)
	if _, err := rand.Read(suffix); err != nil {
		return "", err
	}
	return fmt.Sprintf("%s-%s-%s-%s",
		prefix,
		sanitizeIDPart(principalID),
		now.Format("2006-01-02"),
		hex.EncodeToString(suffix),
	), nil
}

// sanitizeIDPart keeps the principal segment of a token id readable: a
// principal id with whitespace or path-y characters would make the
// resulting token id awkward to reference on the CLI.
func sanitizeIDPart(s string) string {
	if s == "" {
		return "principal"
	}
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '-', c == '_':
			out = append(out, c)
		default:
			out = append(out, '-')
		}
	}
	// Collapse runs of '-' so we do not emit "agent--name".
	collapsed := make([]byte, 0, len(out))
	prevDash := false
	for _, c := range out {
		if c == '-' {
			if prevDash {
				continue
			}
			prevDash = true
		} else {
			prevDash = false
		}
		collapsed = append(collapsed, c)
	}
	// Trim leading/trailing dashes so the id is tidy.
	return strings.Trim(string(collapsed), "-")
}
