// Package runtime is the Phase 3 runtime event substrate. It models
// hook events as durable, queryable evidence of "what actually
// happened" so the dashboard can distinguish "hooks installed but
// silent" from "hooks installed and seeing real activity", and so
// subagents/tasks become first-class actors instead of collapsing
// into the principal id.
//
// Phase 3 contract (see documentation/engineering/specs/2026-04-27-
// phase3-runtime-event-model-spec.md):
//
//   - principal_id stays the policy identity established by the
//     identity resolver. Subagents and tasks NEVER become a
//     principal; they are display + correlation actors only.
//   - the runtime tables sit beside audit_log and activity_events in
//     the same SQLite/Postgres database; migrations are idempotent
//     so a process restart never errors.
//   - this package never imports dashboard, hooks, audit, or
//     connectors/* code; the call direction is one-way (those layers
//     import runtime, never the reverse).
//   - 3A (this PR) only adds the substrate: store, normalizer,
//     tests. 3B integrates the hook handler. UI lives in 3C and 3D.
package runtime

import "time"

// HookEnvelope is the canonical normalized representation of one
// hook POST after identity resolution and before persistence. The
// hook handler builds an envelope from the inbound request and
// hands it to Store.RecordHook; the envelope is the only shape
// downstream callers (Sessions, Graph, Coverage) need to know.
//
// Fields are flat-cased to match the JSON shape we expose on the
// runtime APIs in Phase 3C. Per the spec:
//
//   - RawEvidenceJSON must not contain full tool input/output,
//     secrets, full home paths, or full transcript paths.
//   - PathTail keeps the trailing one or two path components for
//     display; PathHash is a SHA-256 of the original absolute path
//     so two events on the same file correlate without leaking the
//     path.
//   - InputHash and OutputHash are hashes; full content stays under
//     audit/quarantine redaction rules.
//   - ID is generated by Oktsec, never trusted from the payload.
type HookEnvelope struct {
	ID         string
	ReceivedAt time.Time

	ClientID    string // "claude-code" from X-Oktsec-Client
	ConnectorID string // "generic-hooks" unless a named connector is added later
	Surface     string // always "hooks" today

	PrincipalID         string
	PrincipalTrustLevel string
	AuthMethod          string

	SessionID string
	RequestID string

	HookEventName string // PreToolUse, SubagentStart, TaskCreated, ...
	Lifecycle     string // session, tool, subagent, task, config, cwd, permission, stop, notification, file
	Stage         string // pre_action, post_action, observed
	BlockCapable  bool

	Actor         ActorRef
	ParentActorID string
	RootActorID   string

	Tool   ToolRef
	Task   TaskRef
	Config ConfigRef
	File   FileRef

	CWD             string
	CWDHash         string
	TranscriptRef   TranscriptRef
	RawEvidenceJSON string // redacted, bounded
}

// ActorRef captures the runtime actor an event belongs to. Kind
// drives the actor tree shape (root -> subagent | task -> tool).
// ClaudeAgentID and ClaudeAgentType are display-only fields kept
// for correlation; never use them to make a policy decision.
type ActorRef struct {
	ID              string // stable within session: <session_id>:root | :subagent:<id> | :task:<id>
	Kind            string // root, subagent, task, teammate, unknown
	Label           string // display only: Explore, implementer, root
	Source          string // payload, cli_runtime, inferred, unknown
	ClaudeAgentID   string // agent_id when present in the payload
	ClaudeAgentType string // agent_type when present in the payload
}

// ToolRef captures tool-event metadata. InputHash and OutputHash
// keep correlation possible without storing the full payload.
type ToolRef struct {
	Name       string
	UseID      string
	InputHash  string
	OutputHash string
}

// TaskRef captures task-event metadata. Description is redacted +
// truncated upstream of the envelope.
type TaskRef struct {
	ID          string
	Subject     string
	Description string // redacted/truncated by the normalizer
	Teammate    string
	Team        string
}

// ConfigRef captures ConfigChange / InstructionsLoaded metadata.
// Source is one of: user_settings, project_settings,
// local_settings, policy_settings, skills.
type ConfigRef struct {
	Source   string
	PathTail string
	PathHash string
}

// FileRef captures FileChanged metadata. Event is one of: change,
// create, delete.
type FileRef struct {
	PathTail string
	PathHash string
	Event    string
}

// TranscriptRef captures the Claude transcript path for a session
// and (when in a subagent) the subagent transcript path. Both are
// stored as tail+hash so the dashboard can correlate without
// leaking the full file path.
type TranscriptRef struct {
	PathTail      string
	PathHash      string
	AgentPathTail string
	AgentPathHash string
}

// OutcomeRefs links a runtime event back to the audit and activity
// rows it shares evidence with. RecordHook stores these so the
// dashboard can render an event timeline that joins runtime,
// audit, and activity without a full table scan.
//
// All fields are best-effort: a runtime write must never block or
// invalidate the audit/activity write that anchored compliance.
type OutcomeRefs struct {
	AuditEntryID    string
	ActivityEventID string
	Status          string
	PolicyDecision  string
	CoverageMode    string
	Confidence      int
	LatencyMs       int64
}

// Lifecycle constants are exported so the normalizer and downstream
// callers refer to the same strings; keeping them in one place
// avoids the per-event-string drift that bit Phase 1/2.
const (
	LifecycleSession      = "session"
	LifecycleTool         = "tool"
	LifecycleSubagent     = "subagent"
	LifecycleTask         = "task"
	LifecycleConfig       = "config"
	LifecycleCwd          = "cwd"
	LifecycleFile         = "file"
	LifecyclePermission   = "permission"
	LifecycleStop         = "stop"
	LifecycleNotification = "notification"
)

// Stage constants gate runtime decisions like "this row deserves
// the Protected coverage badge" (only pre_action with auth).
const (
	StagePreAction  = "pre_action"
	StagePostAction = "post_action"
	StageObserved   = "observed"
)

// Actor kind constants. The order in the spec is preserved here so
// the dashboard's actor tree renders deterministically.
const (
	ActorKindRoot     = "root"
	ActorKindSubagent = "subagent"
	ActorKindTask     = "task"
	ActorKindTeammate = "teammate"
	ActorKindUnknown  = "unknown"
)

// Actor source constants. Used by the normalizer to record how the
// actor was identified; the dashboard can show "inferred from a
// later tool event" vs "declared at SubagentStart".
const (
	ActorSourcePayload    = "payload"
	ActorSourceCLIRuntime = "cli_runtime"
	ActorSourceInferred   = "inferred_from_tool_event"
	ActorSourceUnknown    = "unknown"
)

// Session status. Active is the default; ended/heartbeat are set
// by SessionEnd or by heartbeat plumbing in 3B.
const (
	SessionStatusActive    = "active"
	SessionStatusEnded     = "ended"
	SessionStatusHeartbeat = "heartbeat"
)

// Connector + surface constants centralised so handler code that
// builds an envelope does not embed string literals.
const (
	ConnectorGenericHooks = "generic-hooks"
	SurfaceHooks          = "hooks"
)
