name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Proxy / message pipeline
        - Identity / signatures
        - Policy engine
        - Detection rules
        - Dashboard
        - Quarantine queue
        - Audit log
        - CLI / UX
        - MCP integration
        - Docker / deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
