package proxy

import (
	"encoding/json"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/oktsec/oktsec/internal/audit"
)

func TestSessionStore_NewAgent_GeneratesID(t *testing.T) {
	s := newSessionStore(30 * time.Minute)
	defer s.Stop()

	id := s.Resolve("agent-a")
	if id == "" {
		t.Fatal("expected non-empty session ID")
	}
	if len(id) != 32 {
		t.Errorf("session ID length = %d, want 32 (hex-encoded 16 bytes)", len(id))
	}
}

func TestSessionStore_SameAgent_SameSession(t *testing.T) {
	s := newSessionStore(30 * time.Minute)
	defer s.Stop()

	id1 := s.Resolve("agent-a")
	id2 := s.Resolve("agent-a")
	if id1 != id2 {
		t.Errorf("same agent should return same session ID: got %q and %q", id1, id2)
	}
}

func TestSessionStore_DifferentAgents_DifferentSessions(t *testing.T) {
	s := newSessionStore(30 * time.Minute)
	defer s.Stop()

	idA := s.Resolve("agent-a")
	idB := s.Resolve("agent-b")
	if idA == idB {
		t.Errorf("different agents should have different session IDs: both %q", idA)
	}
}

func TestSessionStore_Expiry(t *testing.T) {
	// Use a very short TTL so we can test expiry without sleeping.
	s := &sessionStore{
		sessions: make(map[string]*agentSession),
		ttl:      50 * time.Millisecond,
		done:     make(chan struct{}),
	}
	defer s.Stop()

	id1 := s.Resolve("agent-a")

	// Wait for the session to expire
	time.Sleep(100 * time.Millisecond)

	id2 := s.Resolve("agent-a")
	if id1 == id2 {
		t.Errorf("expired session should generate new ID: got same %q", id1)
	}
}

func TestSessionStore_TouchRefreshes(t *testing.T) {
	s := &sessionStore{
		sessions: make(map[string]*agentSession),
		ttl:      100 * time.Millisecond,
		done:     make(chan struct{}),
	}
	defer s.Stop()

	id1 := s.Resolve("agent-a")

	// Resolve again before TTL expires to refresh
	time.Sleep(60 * time.Millisecond)
	id2 := s.Resolve("agent-a")

	// Wait a bit more (total 110ms from first, but only 50ms from refresh)
	time.Sleep(50 * time.Millisecond)
	id3 := s.Resolve("agent-a")

	if id1 != id2 || id2 != id3 {
		t.Errorf("session should stay alive via refresh: %q, %q, %q", id1, id2, id3)
	}
}

func TestSessionStore_Concurrent(t *testing.T) {
	s := newSessionStore(30 * time.Minute)
	defer s.Stop()

	var wg sync.WaitGroup
	ids := make([]string, 100)

	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			ids[idx] = s.Resolve("agent-concurrent")
		}(i)
	}
	wg.Wait()

	// All should be the same session ID (first one wins, rest reuse)
	first := ids[0]
	for i, id := range ids {
		if id != first {
			t.Errorf("ids[%d] = %q, want %q", i, id, first)
		}
	}
}

func TestSessionStore_Evict(t *testing.T) {
	s := &sessionStore{
		sessions: make(map[string]*agentSession),
		ttl:      50 * time.Millisecond,
		done:     make(chan struct{}),
	}
	defer s.Stop()

	_ = s.Resolve("agent-a")
	_ = s.Resolve("agent-b")

	time.Sleep(100 * time.Millisecond)
	s.evict()

	s.mu.RLock()
	count := len(s.sessions)
	s.mu.RUnlock()

	if count != 0 {
		t.Errorf("evict should remove expired sessions, got %d remaining", count)
	}
}

func TestHandler_SessionID_AutoGenerated(t *testing.T) {
	ts := newTestSetup(t, false)

	msg := MessageRequest{
		From:      "test-agent",
		To:        "target-agent",
		Content:   "hello session test",
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}

	// First message — generates a session ID
	w1 := postMessage(ts.handler, msg)
	if w1.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w1.Code)
	}

	// Wait for async audit write
	ts.auditStore.Flush()

	entries, err := ts.auditStore.Query(audit.QueryOpts{Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) == 0 {
		t.Fatal("expected at least one audit entry")
	}
	sessionID := entries[0].SessionID
	if sessionID == "" {
		t.Fatal("expected non-empty session_id in audit entry")
	}
	if len(sessionID) != 32 {
		t.Errorf("session_id length = %d, want 32", len(sessionID))
	}

	// Second message from same agent — same session ID
	msg.Content = "hello again"
	msg.Timestamp = time.Now().UTC().Format(time.RFC3339)
	w2 := postMessage(ts.handler, msg)
	if w2.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w2.Code)
	}

	ts.auditStore.Flush()

	entries2, err := ts.auditStore.Query(audit.QueryOpts{Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	if len(entries2) == 0 {
		t.Fatal("expected audit entry for second message")
	}
	if entries2[0].SessionID != sessionID {
		t.Errorf("second message session_id = %q, want %q", entries2[0].SessionID, sessionID)
	}
}

func TestHandler_SessionID_ExplicitHeader(t *testing.T) {
	ts := newTestSetup(t, false)

	explicitID := "my-custom-session-id-123"
	msg := MessageRequest{
		From:      "test-agent",
		To:        "target-agent",
		Content:   "hello with explicit session",
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}

	w := postMessageWithHeaders(ts.handler, msg, map[string]string{
		"X-Oktsec-Session": explicitID,
	})
	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w.Code)
	}

	var resp MessageResponse
	if err := json.NewDecoder(w.Body).Decode(&resp); err != nil {
		t.Fatal(err)
	}

	ts.auditStore.Flush()

	entries, err := ts.auditStore.Query(audit.QueryOpts{Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) == 0 {
		t.Fatal("expected audit entry")
	}
	if entries[0].SessionID != explicitID {
		t.Errorf("session_id = %q, want %q", entries[0].SessionID, explicitID)
	}
}

func TestGenerateSessionID_Unique(t *testing.T) {
	seen := make(map[string]bool, 1000)
	for i := 0; i < 1000; i++ {
		id := generateSessionID()
		if seen[id] {
			t.Fatalf("duplicate session ID after %d iterations: %s", i, id)
		}
		seen[id] = true
	}
}
