package llm

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	llmAnalysisTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "analysis_total",
		Help:      "Total LLM analyses by status and provider.",
	}, []string{"status", "provider"})

	llmAnalysisLatency = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "analysis_latency_seconds",
		Help:      "LLM analysis latency in seconds.",
		Buckets:   []float64{0.5, 1, 2, 5, 10, 30},
	}, []string{"provider"})

	llmTokensUsed = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "tokens_total",
		Help:      "Total LLM tokens consumed.",
	}, []string{"provider", "model"})

	llmQueueDepth = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "queue_depth",
		Help:      "Current LLM analysis queue depth.",
	})

	llmRulesGenerated = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "rules_generated_total",
		Help:      "Total deterministic rules auto-generated by LLM.",
	})

	llmThreatsDetected = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "threats_detected_total",
		Help:      "Novel threats detected by LLM analysis.",
	}, []string{"type", "severity"})

	llmBudgetSpent = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "budget_spent_usd",
		Help:      "Current LLM spending in USD.",
	}, []string{"period"})

	llmBudgetExhausted = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "budget_exhausted_total",
		Help:      "Number of times LLM budget limit was hit.",
	})

	llmStage1Total = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "stage1_total",
		Help:      "Two-stage classification Stage 1 results (clean skips full analysis, flagged proceeds).",
	}, []string{"result"})

	llmFallbackTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "fallback_total",
		Help:      "Number of times the fallback LLM provider was used.",
	})

	escalationsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "escalations_active",
		Help:      "Number of agents currently under LLM-driven verdict escalation.",
	})

	escalationsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "oktsec",
		Subsystem: "llm",
		Name:      "escalations_total",
		Help:      "Total LLM-driven verdict escalations applied.",
	})
)
